# see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Raspberry Pi Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./raspberry_pi

    container: wpilib/roborio-cross-ubuntu:2024-22.04
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt install -y python3-aiohttp
          python -m pip install --upgrade pip
          pip install pytest
          pip install numpy
          pip install robotpy
          pip install robotpy-cscore
          pip install robotpy-apriltag
          pip install opencv-python
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: Test with pytest
        run: |
          # exclude network test because it segv's
          pytest -k 'not network'
